namespace SafeMobileBrowser.Helpers
{
    public static class Constants
    {
        public const string AppName = "SAFE Browser";
        public const string AppId = "net.maidsafe.safe-browser";
        public const string Vendor = "MaidSafe.net Ltd";
        public const string AppStateMdEntryKey = "safeBrowserState";
        public const string HardCodedAuthResponse = "bAEAAAAAOS4US2AQAAAAAAAAAAAMQAAAAAAAAAAAQAAAAAAAAAAADCN" +
            "ZYFY3DELRXGYXDQORVGQ4DGEYAAAAAAAAAAAYTGOBOGY4C4MJYGUXDEMJYHI2TIOBTCIAAAAAAAAAAAMJTHAXDMOBOGE4DC" +
            "LRVG45DKNBYGMJAAAAAAAAAAABRGM4C4NRYFYYTQMJOGYYDUNJUHAZREAAAAAAAAAAAGEZTQLRWHAXDCOBRFY4DMORVGQ4DG" +
            "EQAAAAAAAAAAAYTGOBOGY4C4MJYGEXDQNZ2GU2DQMYTAAAAAAAAAAADCMZYFY3DQLRRHAYS4MJWHA5DKNBYGMJQAAAAAAAAA" +
            "ABRGM4C4NRYFYYTQMJOGE3TMORVGQ4DGEYAAAAAAAAAAAYTGOBOGY4C4MJYGEXDCNZZHI2TIOBTCMAAAAAAAAAAAMJTHAXDM" +
            "OBOGE4DCLRRHAYDUNJUHAZRGAAAAAAAAAAAGEZTQLRWHAXDCOBRFYYTQMR2GU2DQMYTAAAAAAAAAAADCMZYFY3DQLRRHAYS4" +
            "MRUGI5DKNBYGMJQAAAAAAAAAABRGM4C4NRYFYYTQMJOGI2DGORVGQ4DGEYAAAAAAAAAAAYTGOBOGY4C4MJYGEXDENBZHI2TIO" +
            "BTCIAAAAAAAAAAAMJTHAXDMOBOGE4DSLRRGQ5DKNBYGMJAAAAAAAAAAABRGM4C4NRYFYYTQOJOGE2TUNJUHAZREAAAAAAAAAA" +
            "AGEZTQLRWHAXDCOBZFYYTOORVGQ4DGEQAAAAAAAAAAAYTGOBOGY4C4MJYHEXDCOB2GU2DQMYSAAAAAAAAAAADCMZYFY3DQLRR" +
            "HA4S4MJZHI2TIOBTCIAAAAAAAAAAAMJTHAXDMOBOGE4DSLRTGE5DKNBYGMJAAAAAAAAAAABRGM4C4NRYFYYTQOJOGM2DUNJUHA" +
            "ZREAAAAAAAAAAAGEZTQLRWHAXDCOBZFYZTMORVGQ4DGEQAAAAAAAAAAAYTGOBOGY4C4MJYHEXDGOB2GU2DQMYSAAAAAAAAAAAD" +
            "CMZYFY3DQLRRHA4S4MZZHI2TIOBTCEAAAAAAAAAAANBWFYYTAMJOGUXDCNZZHI2TIOBTAFVRKAAAAAAAAAIHAAAAAAAAAAAGC3" +
            "DQNBQV6MQAAA";

        public const string ConnectingProgressText = "Connecting to the SAFE Network";
        public const string BookmarkRemovedSuccessfully = "Bookmark removed successfully";
        public const string BookmarkAddedSuccessfully = "Bookmark added successfully";

        // URL
        public const string PrivacyInfoUrl = "https://safenetwork.tech/privacy/";
        public const string FaqUrl = "https://safenetforum.org/t/safe-mobile-browser-faqs/";
    }
}
